// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMBzfAnr0UImfkqvoW1qG9wjC-w5-VqYs',
    appId: '1:783029460086:web:dc436de16fcdf1ed911357',
    messagingSenderId: '783029460086',
    projectId: 'ecommerceapp-sportshop',
    authDomain: 'ecommerceapp-sportshop.firebaseapp.com',
    storageBucket: 'ecommerceapp-sportshop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5BSVCynRmizNLMoFOEEHPn7akp6sEzoU',
    appId: '1:783029460086:android:6538215d47f90b8c911357',
    messagingSenderId: '783029460086',
    projectId: 'ecommerceapp-sportshop',
    storageBucket: 'ecommerceapp-sportshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHBML5PWdEfQ4CQ3uQyU4437wTqFtCqw0',
    appId: '1:783029460086:ios:7c61e1a321626fb8911357',
    messagingSenderId: '783029460086',
    projectId: 'ecommerceapp-sportshop',
    storageBucket: 'ecommerceapp-sportshop.appspot.com',
    androidClientId:
        '783029460086-h6r2irtfdb76qaaoldbl12lcru0hjm80.apps.googleusercontent.com',
    iosClientId:
        '783029460086-thmu1fo4ck9c5hrh4hob9tj6tl3kid7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHBML5PWdEfQ4CQ3uQyU4437wTqFtCqw0',
    appId: '1:783029460086:ios:e7712cc8e82b1d5f911357',
    messagingSenderId: '783029460086',
    projectId: 'ecommerceapp-sportshop',
    storageBucket: 'ecommerceapp-sportshop.appspot.com',
    androidClientId:
        '783029460086-h6r2irtfdb76qaaoldbl12lcru0hjm80.apps.googleusercontent.com',
    iosClientId:
        '783029460086-fhs0jgkopsm6396dkf35jaatg6rt3vu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportshop.RunnerTests',
  );
}
